const COUNTRY_NAMES: Record<string, string> = {
  'US': 'United States',
  'GB': 'United Kingdom',
  'DE': 'Germany',
  'FR': 'France',
  'CA': 'Canada',
  'AU': 'Australia',
  'JP': 'Japan',
  'NL': 'Netherlands',
  'BR': 'Brazil',
  'IN': 'India',
  'IT': 'Italy',
  'ES': 'Spain',
  'KR': 'South Korea',
  'SG': 'Singapore',
  'CH': 'Switzerland',
  'SE': 'Sweden',
  'NO': 'Norway',
  'DK': 'Denmark',
  'FI': 'Finland',
  'AT': 'Austria',
  'PL': 'Poland',
  'CZ': 'Czech Republic',
  'RU': 'Russia',
  'UA': 'Ukraine',
  'TR': 'Turkey',
  'ZA': 'South Africa',
  'AE': 'United Arab Emirates',
  'MX': 'Mexico',
  'AR': 'Argentina',
  'CL': 'Chile',
  'TH': 'Thailand',
  'VN': 'Vietnam',
  'ID': 'Indonesia',
  'MY': 'Malaysia',
  'PH': 'Philippines',
  'NZ': 'New Zealand',
  'IE': 'Ireland',
  'PT': 'Portugal',
  'GR': 'Greece',
  'HU': 'Hungary',
  'IS': 'Iceland',
  'LU': 'Luxembourg',
  'EE': 'Estonia',
  'LV': 'Latvia',
  'LT': 'Lithuania',
  'HR': 'Croatia',
  'BG': 'Bulgaria',
  'RO': 'Romania',
  'SK': 'Slovakia',
  'SI': 'Slovenia',
  'CY': 'Cyprus',
  'MT': 'Malta',
  'CO': 'Colombia',
  'PE': 'Peru',
  'VE': 'Venezuela',
  'NG': 'Nigeria',
  'EG': 'Egypt',
  'MA': 'Morocco',
  'KE': 'Kenya',
  'PK': 'Pakistan',
  'BD': 'Bangladesh',
  'TW': 'Taiwan',
  'HK': 'Hong Kong',
  'IL': 'Israel',
  'SA': 'Saudi Arabia',
  'QA': 'Qatar',
  'KW': 'Kuwait',
  'BH': 'Bahrain',
  'OM': 'Oman',
  'JO': 'Jordan',
  'LB': 'Lebanon',
  'IQ': 'Iraq',
  'IR': 'Iran',
}

export function getCountryName(code: string): string {
  return COUNTRY_NAMES[code.toUpperCase()] || code
}